{
  "_id":"_design/carplots",
  "_rev":"16-58573203b24ace840075bc6294085a1c",
  "lists":{
    "key_value":"#"
  },
  "rewrites":[
    {
      "from":"/plots/:mmid/:yr",
      "query":{
        "endkey":[
          ":mmid",
          ":yr",
          {}
        ],
        "startkey":[
          ":mmid",
          ":yr"
        ]
      },
      "to":"/_list/key_value/plots"
    },
    {
      "from":"/plots/:mmid/:yr/:eng",
      "query":{
        "key":[
          ":mmid",
          ":yr",
          ":eng"
        ]
      },
      "to":"/_list/key_value/plots"
    }
  ],
  "views":{
    "plots":{
      "map":"#"
    }
  }
}